### ISSUE TITLE
I can't access the minecraft console/attach to the container.

### ISSUE THREAD

**Issue by Trevo525** [cooperspencer/purpur-docker#1]
I know it's not your problem, but if you could help me I would appreciate it. I cannot for the life of me, attach to the container. I am using a docker-compose.yml file as follows:

```
version: '2'
services:
    'purpur':
        image: 'buddyspencer/purpur:1.18.2'
        container_name: purpur-mc
        environment:
            - MEMORYSIZE=2G
        volumes:
            - './data:/data:rw'
        ports:
            - '25565:25565'
```

Maybe that is what is causing it? So, I used the file above with `docker-compose up -d` and then tried `docker attach purpur-mc`. It appears to attach. I can type and text will show but commands don't go through. I can't CTRL+C to close. CTRL+P and CTRL+Q don't close it. I have to close out the terminal and ssh back in. It becomes fully irresponsible.

![2022-03-17 21_09_38-docker](https://user-images.githubusercontent.com/21350315/158918508-4612975f-93a9-408f-be34-00966ec411d2.png)

I could edit the ops.json file, but I want to do some other things, like run [Chunky](https://www.spigotmc.org/resources/chunky.81534/) so I would like to access the Minecraft console.

**Comment by cooperspencer** [comment]
hi,
you can add `stdin_open: true` to your compose file, then you should be able to attach to the container

**Comment by Trevo525** [comment]
Thank you so much! I don't know how I missed that but I appreciate your help!

Final docker-compose.yml
```
version: '2'
services:
    'purpur':
        image: 'buddyspencer/purpur:1.18.2'
        container_name: purpur-mc
        stdin_open: true
        environment:
            - MEMORYSIZE=2G
        volumes:
            - './data:/data:rw'
        ports:
            - '25565:25565'
```
